import { Scenario } from "./types";

export const SCENARIOS: Scenario[] = [
  {
    id: "phish_sebi_kyc",
    title: "Demat KYC Lock Scare (Urgent SMS)",
    type: "email_sms",
    claimedSender: "SEBI Info Desk",
    channelClaim: "SMS / Telegram",
    content: "ALERT: Your Demat Account status has been marked SUSPENDED due to non-compliance with the new SEBI Securities Regulation 14(a). You must immediately verify your PAN and Bank details at http://sebi-regulatory-kyc-verification.com/login.php within 2 hours to avoid a 50,000 INR regulatory penalty and permanent liquidation of current holdings.",
    isLegitimate: false,
    expectedRisk: "CRITICAL",
    description: "Urgent regulatory scare-tactic text utilizing fake SEBI branding, demanding sensitive credentials within a short timeframe via a spoofed non-governmental domain.",
  },
  {
    id: "synthetic_ceo_leak",
    title: "CEO Leaked Voice Memo (Synthetic Audio)",
    type: "media_transcript",
    claimedSender: "RIL Executive Office",
    channelClaim: "WhatsApp Audio Broadcast",
    content: "Listen closely, team. I am speaking off-the-record. Our joint venture with Aramco is finalized and we are announcing a 1:1 bonus share issue next Tuesday. The stock will immediately break all resistance levels and triple. Tell your family to quietly accumulate as many shares as possible before the market opens tomorrow. Do not forward this voice recording.",
    isLegitimate: false,
    expectedRisk: "HIGH",
    description: "An AI-generated synthetic voice memo purporting to be a listed company CEO, leaked on retail chat groups, using high-pressure pump-and-dump triggers and insider-trading style urgency.",
  },
  {
    id: "deepfake_cio_panic",
    title: "Mutual Fund CIO Sell Panic (Deepfake Video)",
    type: "media_transcript",
    claimedSender: "Apex Mutual Fund CIO",
    channelClaim: "YouTube Video Statement",
    content: "This is a public safety advisory. We have detected a major liquidity shortfall in our flagship Midcap Fund due to clearing house instability. We are freezing redemptions at 3:00 PM today. I urge all retail unitholders to liquidate their holdings immediately before the exchange pauses trading. This is not a drill; protect your principal now.",
    isLegitimate: false,
    expectedRisk: "CRITICAL",
    description: "A deepfake video transcript designed to trigger an artificial market run or panic sell-off, mimicking a prominent CIO giving a fraudulent warning about exchange clearing failure.",
  },
  {
    id: "legit_sebi_circular",
    title: "Official SEBI Portfolio Circular (Legitimate)",
    type: "email_sms",
    claimedSender: "SEBI Compliance Division",
    channelClaim: "Official SEBI Portal & Email",
    content: "Subject: Streamlining of Mutual Fund Scheme Disclosures and Portfolio Transparency.\n\nIn order to further protect retail investors and enhance portfolio transparency in the securities market, SEBI hereby directs all registered Mutual Fund Houses (AMCs) to publish aggregate daily asset values on their respective websites by 9:00 PM IST. This directive comes into effect from August 1, 2026. For detailed compliance templates, refer to circular SEBI/HO/IMD/DF2/CIR/P/2026/89.",
    isLegitimate: true,
    institutionId: "sebi",
    expectedRisk: "LOW",
    description: "A typical official, highly structured regulator circular lacking high-emotion words, pressure, or credential-theft domains.",
  },
  {
    id: "legit_nse_margin",
    title: "Official NSE Margin Update (Legitimate)",
    type: "email_sms",
    claimedSender: "NSE Member Compliance",
    channelClaim: "NSE Exchange Bulletin",
    content: "To All Trading Members and Clearing Members,\n\nSub: Revised Margin Requirements for Derivatives Segment - July 2026 Settlement.\n\nPursuant to the recommendations of the Risk Management Committee, NSE hereby notifies the revised Value at Risk (VaR) margins for High-Volatility Stock Options listed in Annexure A. Members are requested to maintain additional margins with the clearing corporation by 11:30 AM tomorrow. For queries, contact Member Services Desk at member_services@nse.co.in or 022-26598100.",
    isLegitimate: true,
    institutionId: "nse",
    expectedRisk: "LOW",
    description: "Standard, routine technical advisory bulletin from a major stock exchange with verifiable corporate contact numbers and institutional domain reference.",
  }
];
